version: "3.8"
services:
  web3signer:
    image: pegasyseng/web3signer:21.10.5
  teku:
    image: pegasyseng/teku:22.1.1
  lighthouse:
    image: sigp/lighthouse:v2.1.3
  nimbus:
  lodestar:
  auto-check:
    build:
      context: ./build
      dockerfile: Dockerfile
    env:
      RUST_ENV: development
      RUST_BACKTRACE: 1
      ETH2_CLIENT_API_URL: http://validator.lighthouse-prater.dappnode:9000
      WEB3SIGNER_API_URL: http://web3signer.web3signer-prater.dappnode:9000
